language: bash
sudo: required

before_install:
  - sudo apt-get update -q
  - sudo apt-get install cabal-install  -y
  - cabal update
  - cabel install shellcheck
script:
  - ~/.cabal/bin/shellcheck bashadventures

